version: '3'
services:
  web:
    image: nginx:alpine
    container_name: d8-nginx
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/ssl:/etc/ssl
      - ${DRUPAL_FOLDER}:/var/www/html/drupal
      - ./etc/nginx/default.drupal.conf:/etc/nginx/conf.d/default.drupal
    ports:
      - 8000:80
      - 3000:443
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.drupal > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    links:
      - php
      - db
  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    container_name: d8-php
    restart: always
    volumes:
      - ./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ${DRUPAL_FOLDER}:/var/www/html/drupal
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - ./data/db/mysql:/var/lib/mysql
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
  memcached:
    container_name: d8-memcached
    image: wodby/memcached:1.4-2.0.0
